apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNakV3TWpNeApNelV5TURkYUZ3MDBNakV3TWpNeE16VXlNRGRhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEUTdhZlFreGZoQ3g4RGF0N2VXRlEzSHd1blZqR2lTaUZIckdzK1dRWDhHeFNaekZiRwpINTZHWklFVitweTIrSlE4ai9zcVFoS1d2R1pVUEVTbTJpcXR2YmFpVWNIckZRNGZkQ1Rma0hvOC9hMHlLQWZzCmwzUjdNVUdVTngzaUwrd0VJVW5HMW5WbjlIR0Z1WVpWMHJkbE92M1p3bGppMmhYMndncm8wZDNpL3FpT0lKcU8KaHRPZ2FTSnplMHZsMDltaitaVDg3RE45MjJGYkUyUUk0YkVBTHJ4Ti96eGhTMWZZWGNEczdMR0E1YXhqY3NIdgpmV3d6aTROUnB6T2tLN0doN3FIaXVBVDlmZVd2MFZ6Uy92SkcxRno0MG1mbURIbjA4YUNMZW1wUFVPa1hpR0NYCmJ1L1Ywak9iSUxtOGZuZWNxUy9ZU3F4dEdhZTM1UUdLTWh1dkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlNCMHFVN21vKzcwWWxJOWFJZwovTnZJOGpHMzZEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUF1cytRbnkzTGpzdWlWdUNZUXRZVis4cWRzRmVZClFsRVp4ZUkyQlA5MjdIcUJwaEE3QkFramhUai9oVlphWnRGVjY2Wk5IRWFKcFZjZUIzTXBPcW1qNFpUcUNPcXIKNlVycnpiTmZzc2N4eVBKRnZzU0JiekdkRzcxaVNwVENobi9CSk96S2YrRmdCVGhyck9qMnlDZU05SDNEVEFOZgpLZmw5T0ZkSGY2NDEzWG5Ga2ZwcEdGU3FxWTUrMVhTNlU0b2o4N0Q3Ly9XdXFNcXYzOExOWFlnbWpobHJNMmloCjVjZzNGaFdHelJ0N0xzd2tlRjhwWm1WZ25oQnpEcCtiT3QwSzBWZS81Z2xkUGxqRFozQjdSbVE4aEE2M2ZjSCsKRERvTW9Lb2hGc2I0TkV1L0t3NlAwVk5TU2dwdm43UExUaS81S0kySzFrZGdMUzNkL1RUenVPdEhlQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://d5e34361-3264-4415-a0f3-27132aad3f17.k8s.ondigitalocean.com
  name: do-nyc1-k8s
contexts:
- context:
    cluster: do-nyc1-k8s
    user: do-nyc1-k8s-admin
  name: do-nyc1-k8s
current-context: do-nyc1-k8s
users:
- name: do-nyc1-k8s-admin
  user:
    token: dop_v1_ee5da7cd652bbe9daaf3dfc9376fdf6c978113e8cacf9c605bcc04f55135c52f
